// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDWroxln5aDwJmZi8r_uMxw-gkItl4Ecg',
    appId: '1:86951492174:android:a2e2687e04ac69b333211f',
    messagingSenderId: '86951492174',
    projectId: 'kit712assignment',
    storageBucket: 'kit712assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXhkL6ohXxkIwJmYJ6TVRCKB3G7J20RdA',
    appId: '1:86951492174:ios:4e996b4a6a208f0733211f',
    messagingSenderId: '86951492174',
    projectId: 'kit712assignment',
    storageBucket: 'kit712assignment.appspot.com',
    iosBundleId: 'au.edu.utas.multicricket.multicricket',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApjkldl2VQPaiV_BsvasnQuUSFlKxR65o',
    appId: '1:86951492174:web:17535c2765b6f3e633211f',
    messagingSenderId: '86951492174',
    projectId: 'kit712assignment',
    authDomain: 'kit712assignment.firebaseapp.com',
    storageBucket: 'kit712assignment.appspot.com',
  );

}